/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONObject;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.whu.tools.DBTools;
import com.whu.tools.SystemConstant;
import com.whu.web.common.SystemShare;
import com.whu.web.event.EventBean;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2013
 * 
 * XDoclet definition:
 * @struts.action path="/approveEventAction" name="approveEventForm" parameter="method" scope="request" validate="true"
 */
public class ApproveEventAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	/**
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws IOException 
	 */
	public ActionForward approve(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.setContentType("text/html;charset=utf-8");
		request.setCharacterEncoding("utf-8");
		ApproveEventForm checkEventForm = (ApproveEventForm) form;
		String reportID = request.getParameter("reportID");
		String isLA = checkEventForm.getIsLA();
		String laAdvice = checkEventForm.getLaAdvice();
		String approveName = checkEventForm.getApproveName();
		String approveTime = SystemShare.GetNowTime("yyyy-MM-dd");
		
		String status = "";
		String fkInfo = "";
		String flowStr = "";
		String processStr = "";
		String gyDesc = "";
		if(isLA.equals("1"))
		{
			//调查中
			status = SystemConstant.SS_SURVEYING;
			fkInfo = SystemConstant.FK_APPROVEEVENT1;
			processStr = SystemConstant.HP_KZDC;
			flowStr = SystemConstant.LCT_LADC;
			gyDesc = approveTime + "，领导审核完毕，对该举报事件开展调查！";
		}
		else if(isLA.equals("0"))
		{
			//未立案
			status = SystemConstant.SS_UNLA;
			fkInfo = SystemConstant.FK_APPROVEEVENT2;
			processStr = SystemConstant.HP_NOKZDC;
			flowStr = SystemConstant.LCT_BYLA;
			gyDesc = approveTime + "，领导审核完毕，对该举报事件不予开展调查！";
		}
		
		DBTools db = new DBTools();
		
		String sql = "insert into TB_APPROVEINFO(REPORTID,ISLA,LAADVICE,APPROVENAME,APPROVETIME) values('" + reportID + "','" + isLA + "','" + laAdvice + "','" + approveName +"','" + approveTime + "')";
		boolean result = db.insertItem(sql);
		
		if(result)
		{
			sql = "update TB_REPORTINFO set STATUS='" + status + "',LASTTIME='" + approveTime + "' where REPORTID='"+ reportID + "'";
			result = db.insertItem(sql);
			
			//更新消息提醒状态，使得“事件审批”栏目不会再重复出现该事件
			String loginName = (String)request.getSession().getAttribute("UserName");
			sql = "update TB_MSGNOTIFY set ISHANDLE='1' where RECVNAME='" + loginName + "' and REPORTID='" + reportID + "'";
			db.insertItem(sql);
			
			//插入处理过程到数据库中
			String describe = approveTime + "领导：" + approveName + "审批该事件,审核意见详情请查看《审核信息》一栏";
			db.InsertHandleProcess(reportID, approveName, SystemConstant.HP_APPROVEEVENT, SystemConstant.SS_SURVEYING, SystemConstant.LCT_LDSP, describe);
			
			//控制“立案调查”和“不予调查”的流程图节点的显示
			db.InsertHandleProcess(reportID, approveName, processStr, SystemConstant.SS_SURVEYING, flowStr, gyDesc);
			
			//插入反馈信息到门户数据库中
			db.InsertFKInfo(reportID, fkInfo, approveTime);
			
			//写入日志文件
			db.insertLogInfo(loginName, SystemConstant.LOG_APPROVE, "审批事件是否立案，事件编号为：" + reportID, request.getRemoteAddr());
		}
		PrintWriter out = response.getWriter();
		JSONObject json = new JSONObject();
		if(result)
		{
			json.put("statusCode", 200);
			json.put("message", "审核成功！");
			json.put("callbackType", "closeCurrent");
		}
		else
		{
			json.put("statusCode", 300);
			json.put("message", "事件审核失败");
		}
		out.write(json.toString());
		out.flush();
		out.close();
		return null;
	}
}