/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.whu.web.eventmanage;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-03-2013
 * 
 * XDoclet definition:
 * @struts.form name="checkEventForm"
 */
public class CheckEventForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	//事件编号
	private String reportID;
	//初步核实意见
	private String preAdvice;
	//报送领导
	private String bsHead;
	//核实人姓名
	private String checkName;
	//所属学部
	private String faculty;
	public String getFaculty() {
		return faculty;
	}

	public void setFaculty(String faculty) {
		this.faculty = faculty;
	}

	public String getBsHead() {
		return bsHead;
	}

	public void setBsHead(String bsHead) {
		this.bsHead = bsHead;
	}

	public String getReportID() {
		return reportID;
	}

	public void setReportID(String reportID) {
		this.reportID = reportID;
	}

	public String getPreAdvice() {
		return preAdvice;
	}

	public void setPreAdvice(String preAdvice) {
		this.preAdvice = preAdvice;
	}

	public String getCheckName() {
		return checkName;
	}

	public void setCheckName(String checkName) {
		this.checkName = checkName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}